### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by ShungJhon** [davidADSP/Generative_Deep_Learning_2nd_Edition#5]
I've built the docker image successfully. However, when using `docker-compose -f docker-compose-gpu.yml up`, it returns: Starting generative_deep_learning_2nd_edition_app_1 ... error

ERROR: for generative_deep_learning_2nd_edition_app_1  Cannot start service app: could not select device driver "nvidia" with capabilities: [[gpu]]

ERROR: for app  Cannot start service app: could not select device driver "nvidia" with capabilities: [[gpu]]

**Comment by davidADSP** [comment]
Does you device have a GPU set up? Are you Windows, Mac or Linux?

**Comment by ShungJhon** [comment]
It's Ubuntu 20.04 and with a GPU with cuda 11.4. @davidADSP
